export interface NormalizedEvent {
  id: string;
  title: string;
  description: string;
  date: string; // ISO date 'YYYY-MM-DD'
  time: string; // 'HH:mm'
  venue: string;
  address: string;
  city: string;
  state?: string;
  category: string;
  genre?: string;
  imageUrl: string;
  ticketUrl: string;
  minPrice?: number;
  maxPrice?: number;
  currency?: string;
  status: 'active' | 'cancelled' | 'postponed';
  friendsAttendingCount?: number;
  latitude?: number;
  longitude?: number;
}

// Helper to generate dynamic dates relative to today
const getDateOffset = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const MOCK_EVENTS: NormalizedEvent[] = [
  {
    id: 'mock-evt-101',
    title: 'Neon Horizon World Tour: Synthwave Live',
    description: 'Experience an electrifying night of retro-futuristic synthwave beats, laser visual mapping, and live instrumental solos featuring The Midnight & Kavinsky.',
    date: getDateOffset(0), // Today!
    time: '20:00',
    venue: 'Radio City Music Hall',
    address: '1260 6th Ave',
    city: 'New York',
    state: 'NY',
    category: 'Music',
    genre: 'Electronic',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 55,
    maxPrice: 160,
    currency: 'USD',
    status: 'active',
    latitude: 40.7600,
    longitude: -73.9799,
  },
  {
    id: 'mock-evt-102',
    title: 'NBA Showdown: Golden State Warriors vs LA Lakers',
    description: 'Rivalry week returns to the Bay Area! Watch Stephen Curry take on LeBron James in this high-stakes Western Conference basketball clash.',
    date: getDateOffset(1), // Tomorrow
    time: '19:30',
    venue: 'Chase Center',
    address: '1 Warriors Way',
    city: 'San Francisco',
    state: 'CA',
    category: 'Sports',
    genre: 'Basketball',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 85,
    maxPrice: 420,
    currency: 'USD',
    status: 'active',
    latitude: 37.7680,
    longitude: -122.3877,
  },
  {
    id: 'mock-evt-103',
    title: 'Wicked: The Broadway Musical Spectacular',
    description: 'The untold story of the Witches of Oz. Long before Dorothy drops in, two other girls meet in the land of Oz. Winner of over 100 international awards.',
    date: getDateOffset(2),
    time: '19:00',
    venue: 'Gershwin Theatre',
    address: '222 W 51st St',
    city: 'New York',
    state: 'NY',
    category: 'Arts & Theatre',
    genre: 'Musical',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 79,
    maxPrice: 240,
    currency: 'USD',
    status: 'active',
    latitude: 40.7624,
    longitude: -73.9852,
  },
  {
    id: 'mock-evt-104',
    title: 'Austin Indie Film & Sound Festival 2026',
    description: 'A 3-day showcase of cutting-edge independent cinema, director Q&As, and live film scoring workshops across downtown Austin venues.',
    date: getDateOffset(3),
    time: '16:00',
    venue: 'Paramount Theatre',
    address: '713 Congress Ave',
    city: 'Austin',
    state: 'TX',
    category: 'Film',
    genre: 'Festival',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 35,
    maxPrice: 110,
    currency: 'USD',
    status: 'active',
    latitude: 30.2694,
    longitude: -97.7420,
  },
  {
    id: 'mock-evt-105',
    title: 'Coldplay: Music of the Spheres Stadium Experience',
    description: 'The monumental stadium tour powered by 100% renewable kinetic dance floors, kinetic energy, LED wristbands, and iconic sing-alongs.',
    date: getDateOffset(5),
    time: '18:30',
    venue: 'Soldier Field',
    address: '1410 Special Olympics Dr',
    city: 'Chicago',
    state: 'IL',
    category: 'Music',
    genre: 'Pop / Rock',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 95,
    maxPrice: 350,
    currency: 'USD',
    status: 'active',
    latitude: 41.8623,
    longitude: -87.6167,
  },
  {
    id: 'mock-evt-106',
    title: 'Seattle Tech & AI Future Summit',
    description: 'Join pioneering founders, researchers, and engineers exploring next-generation agentic AI, quantum computing, and ethical technology development.',
    date: getDateOffset(6),
    time: '09:00',
    venue: 'Seattle Convention Center',
    address: '705 Pike St',
    city: 'Seattle',
    state: 'WA',
    category: 'Miscellaneous',
    genre: 'Conference',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 120,
    maxPrice: 299,
    currency: 'USD',
    status: 'active',
    latitude: 47.6117,
    longitude: -122.3328,
  },
  {
    id: 'mock-evt-107',
    title: 'Premier League Fan Fest: Chelsea vs Arsenal Live',
    description: 'Immersive outdoor stadium screening with British pub eats, giant 4K LED screens, live commentary, and celebrity player meet & greets.',
    date: getDateOffset(8),
    time: '14:30',
    venue: 'O2 Arena Plaza',
    address: 'Peninsula Square',
    city: 'London',
    state: 'UK',
    category: 'Sports',
    genre: 'Soccer',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 25,
    maxPrice: 85,
    currency: 'GBP',
    status: 'active',
    latitude: 51.5030,
    longitude: 0.0032,
  },
  {
    id: 'mock-evt-108',
    title: 'Trevor Noah: Loud & Clear Comedy Tour',
    description: 'Grammy-nominated comedian and former Daily Show host Trevor Noah takes the stage for a hilarious evening on global politics, travel, and humanity.',
    date: getDateOffset(10),
    time: '20:00',
    venue: 'Beacon Theatre',
    address: '2124 Broadway',
    city: 'New York',
    state: 'NY',
    category: 'Arts & Theatre',
    genre: 'Comedy',
    imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 60,
    maxPrice: 195,
    currency: 'USD',
    status: 'active',
    latitude: 40.7808,
    longitude: -73.9810,
  },
  {
    id: 'mock-evt-109',
    title: 'Kendrick Lamar & SZA: Grand Park Festival',
    description: 'An unforgettable night of Pulitzer-prize winning hip-hop and chart-topping R&B under the starry California sky in downtown Los Angeles.',
    date: getDateOffset(12),
    time: '17:00',
    venue: 'Grand Park Amphitheatre',
    address: '200 N Grand Ave',
    city: 'Los Angeles',
    state: 'CA',
    category: 'Music',
    genre: 'Hip-Hop / Rap',
    imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 90,
    maxPrice: 320,
    currency: 'USD',
    status: 'active',
    latitude: 34.0553,
    longitude: -118.2458,
  },
  {
    id: 'mock-evt-110',
    title: 'Modern Art After Dark: Light & Mirrors Exhibition',
    description: 'An evening museum experience featuring immersive infinity rooms, interactive sound sculptures, cocktail lounge, and guest DJ sets.',
    date: getDateOffset(14),
    time: '18:00',
    venue: 'San Francisco Museum of Modern Art',
    address: '151 3rd St',
    city: 'San Francisco',
    state: 'CA',
    category: 'Arts & Theatre',
    genre: 'Exhibition',
    imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 30,
    maxPrice: 65,
    currency: 'USD',
    status: 'active',
    latitude: 37.7857,
    longitude: -122.4011,
  },
  {
    id: 'mock-evt-111',
    title: 'Formula 1 Grand Prix Austin: Opening Night Concert',
    description: 'High adrenaline meets mega pop music as F1 returns to Austin with live practice sessions followed by a massive trackside stadium concert.',
    date: getDateOffset(18),
    time: '19:00',
    venue: 'Circuit of the Americas',
    address: '9201 Circuit of The Americas Blvd',
    city: 'Austin',
    state: 'TX',
    category: 'Sports',
    genre: 'Motorsports',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 150,
    maxPrice: 650,
    currency: 'USD',
    status: 'active',
    latitude: 30.1346,
    longitude: -97.6411,
  },
  {
    id: 'mock-evt-112',
    title: 'Hans Zimmer Live: Cinematic Symphonic Odyssey',
    description: 'Multiple Academy Award-winning composer Hans Zimmer and his 40-piece orchestra perform the legendary soundtracks of Interstellar, Dune, and The Dark Knight.',
    date: getDateOffset(22),
    time: '19:30',
    venue: 'Madison Square Garden',
    address: '4 Pennsylvania Plaza',
    city: 'New York',
    state: 'NY',
    category: 'Music',
    genre: 'Classical / Soundtrack',
    imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1200&q=80',
    ticketUrl: 'https://www.ticketmaster.com',
    minPrice: 85,
    maxPrice: 280,
    currency: 'USD',
    status: 'active',
    latitude: 40.7505,
    longitude: -73.9934,
  }
];
